{
  "code": 200,
  "data": [
    {
      "vipPrice": 458,
      "vipRealPrice": 0,
      "goodsCode": "V0005",
      "goodsName": "极客空间永久会员+音乐人",
      "detailList": null,
      "sort": 1,
      "goodsShort": "永久+音乐人",
      "goodsStock": 9999,
      "goodsIcon": null,
      "goodsSpec": "2099",
      "delFlag": null,
      "goodsStatus": 1,
      "lastUpdateTime": null,
      "topupHints": [
        {
          "id": 38,
          "createBy": null,
          "delFlag": null,
          "hintType": null,
          "hintSort": null,
          "createTime": null,
          "hintAccount": null,
          "lastUpdateBy": null,
          "hintName": null,
          "lastUpdateTime": null,
          "goodsId": null,
          "hintContent": null,
          "hintLength": null
        }
      ],
      "goodsPic": null,
      "id": 38,
      "labelType": null,
      "realPrice": 179,
      "createBy": null,
      "labelColor": null,
      "createTime": null,
      "goodsType": "geek_vip",
      "price": 458,
      "lastUpdateBy": null
    },
    {
      "vipPrice": 388,
      "vipRealPrice": 129,
      "goodsCode": "V0004",
      "goodsName": "极客空间永久会员",
      "detailList": null,
      "sort": 2,
      "goodsShort": "永久会员",
      "goodsStock": 9999,
      "goodsIcon": null,
      "goodsSpec": "2099",
      "delFlag": null,
      "goodsStatus": 1,
      "lastUpdateTime": null,
      "topupHints": [
        {
          "id": 7,
          "createBy": null,
          "delFlag": null,
          "hintType": null,
          "hintSort": null,
          "createTime": null,
          "hintAccount": null,
          "lastUpdateBy": null,
          "hintName": null,
          "lastUpdateTime": null,
          "goodsId": null,
          "hintContent": null,
          "hintLength": null
        }
      ],
      "goodsPic": null,
      "id": 7,
      "labelType": null,
      "realPrice": 129,
      "createBy": null,
      "labelColor": null,
      "createTime": null,
      "goodsType": "geek_vip",
      "price": 388,
      "lastUpdateBy": null
    },
    {
      "vipPrice": 12,
      "vipRealPrice": 8.99,
      "goodsCode": "V0001",
      "goodsName": "极客空间月卡会员",
      "detailList": null,
      "sort": 3,
      "goodsShort": "月卡会员",
      "goodsStock": 9999,
      "goodsIcon": null,
      "goodsSpec": "30",
      "delFlag": null,
      "goodsStatus": 1,
      "lastUpdateTime": null,
      "topupHints": [
        {
          "id": 3,
          "createBy": null,
          "delFlag": null,
          "hintType": "1",
          "hintSort": "1",
          "createTime": null,
          "hintAccount": "1",
          "lastUpdateBy": null,
          "hintName": "手机号",
          "lastUpdateTime": null,
          "goodsId": 3,
          "hintContent": "手机号",
          "hintLength": 21
        }
      ],
      "goodsPic": "string \/\/商品首页图",
      "id": 3,
      "labelType": "string \/\/标签类型",
      "realPrice": 8.99,
      "createBy": null,
      "labelColor": "string \/\/标签颜色",
      "createTime": null,
      "goodsType": "geek_vip",
      "price": 12,
      "lastUpdateBy": null
    },
    {
      "vipPrice": 30,
      "vipRealPrice": 22.99,
      "goodsCode": "V0002",
      "goodsName": "极客空间季卡会员",
      "detailList": null,
      "sort": 4,
      "goodsShort": "季卡会员",
      "goodsStock": 9999,
      "goodsIcon": null,
      "goodsSpec": "90",
      "delFlag": null,
      "goodsStatus": 1,
      "lastUpdateTime": null,
      "topupHints": [
        {
          "id": 4,
          "createBy": null,
          "delFlag": null,
          "hintType": null,
          "hintSort": null,
          "createTime": null,
          "hintAccount": null,
          "lastUpdateBy": null,
          "hintName": null,
          "lastUpdateTime": null,
          "goodsId": null,
          "hintContent": null,
          "hintLength": null
        }
      ],
      "goodsPic": "string \/\/商品首页图",
      "id": 4,
      "labelType": "string \/\/标签类型",
      "realPrice": 22.99,
      "createBy": null,
      "labelColor": "string \/\/标签颜色",
      "createTime": null,
      "goodsType": "geek_vip",
      "price": 30,
      "lastUpdateBy": null
    },
    {
      "vipPrice": 100,
      "vipRealPrice": 69.98999999999999,
      "goodsCode": "V0003",
      "goodsName": "极客空间年卡会员",
      "detailList": null,
      "sort": 5,
      "goodsShort": "年卡会员",
      "goodsStock": 9999,
      "goodsIcon": null,
      "goodsSpec": "365",
      "delFlag": null,
      "goodsStatus": 1,
      "lastUpdateTime": null,
      "topupHints": [
        {
          "id": 6,
          "createBy": null,
          "delFlag": null,
          "hintType": null,
          "hintSort": null,
          "createTime": null,
          "hintAccount": null,
          "lastUpdateBy": null,
          "hintName": null,
          "lastUpdateTime": null,
          "goodsId": null,
          "hintContent": null,
          "hintLength": null
        }
      ],
      "goodsPic": "string \/\/商品首页图",
      "id": 6,
      "labelType": "string \/\/标签类型",
      "realPrice": 69.98999999999999,
      "createBy": null,
      "labelColor": "string \/\/标签颜色",
      "createTime": null,
      "goodsType": "geek_vip",
      "price": 100,
      "lastUpdateBy": null
    }
  ],
  "msg": "成功",
  "total": 0
}
